#!/bin/sh

# CHARLES EDITS AT THE TOP

# for connecting to my bluetooth audio devies. The bluetooth.service service is set to run at boot in systemd

speaker() { # connect to my tribit xsound go speaker
	echo 'power on' | bluetoothctl
	echo 'connect F4:4E:FD:D0:8C:00' | bluetoothctl
}

ears() { # connect to my jabra elite 85t earbuds
	echo 'power on' | bluetoothctl
	echo 'connect 30:50:75:AF:00:9C' | bluetoothctl
}

dc() { # disconnect both the speaker and earbuds
	echo 'disconnect 30:50:75:AF:00:9C' | bluetoothctl
	echo 'disconnect 30:50:75:AF:00:9C' | bluetoothctl
	echo 'power off' | bluetoothctl
}

# for connecting the the UMass UNIX server
alias umb="sshpass -p XtraUMB11!! ssh charles@users.cs.umb.edu"

# for charlesw.xyz and whittlesey.xyz login
alias charlesw="sshpass -p '*6Na8.-57qJ=?So_' ssh root@charlesw.xyz"

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
